### ISSUE TITLE
Compatibility with Sonar 5.6

### ISSUE THREAD

**Issue by marcoblos** [SonarQubeCommunity/sonar-build-breaker#11]
Hi

I would like to know whether version 2.1 is compatible with Sonar 5.6?

**Comment by mjdetullio** [comment]
Should be.  Test it out

**Comment by marcoblos** [comment]
I try to push the update on readme, containing the information that build breaker work with SonarQube 5.6 LTS, but I haven't permission to commit within repository.
@mjdetullio do you can the update the readme? I tested in my project and the build-breaker work fine.
Thanks.

**Comment by mjdetullio** [comment]
Done
