### ISSUE TITLE
API query limit (30) reached

### ISSUE THREAD

**Issue by ddavison** [SonarQubeCommunity/sonar-build-breaker#13]
*Foreword*: this may not even be an issue - I'm just not sure where to put the buildbreaker properties.

per [QualityGateBreaker.java:159](https://github.com/SonarQubeCommunity/sonar-build-breaker/blob/master/src/main/java/org/sonar/plugins/buildbreaker/QualityGateBreaker.java#L159) this plugin will break if the API query limit is exceeded.

I've attempted to modify `/usr/local/sonar/conf/sonar.properties` and add

```properties
sonar.buildbreaker.queryMaxAttempts=100
sonar.buildbreaker.queryInterval=10000
```

but it doesn't seem to be reading these at all!  It still says `"queryMaxAttempts"` is `30`.  **Am I putting these properties in the wrong place?**

How can I apply these properties successfully?

**Comment by mjdetullio** [comment]
I'm guessing this is the server-side properties file you're modifying.  I haven't tried defining properties there.  You should use the Administration pages in the SQ server's web UI to update the global default values for these settings if you wish to define them server-side.

The plugin simply loads the setting from an injected SQ core/plugin API, so property loading isn't really handled by this plugin.  My guess is there is no provision for the scanner to read settings from the server-side `sonar.properties` file, or it's an SQ bug.

**Comment by mjdetullio** [comment]
And note that http://docs.sonarqube.org/display/SONAR/Analysis+Parameters does not specifically mention the server-side `sonar.properties` as a location to define analysis parameters.  My guess is that this file is reserved for settings which are not used during analysis.  All Build Breaker settings are analysis parameters.

**Comment by ddavison** [comment]
let me take a look through the admin pages of SQ.  ok so if they can't be in `sonar.properties`, is there a file dedicated for the build-breaker specific properties?

**Comment by ddavison** [comment]
the reason i ask, is because I use configuration management to manage sonarqube.  without logging into the UI, was just curious if there was a way to specify these.

*by the way*, I did find those settings you mentioned.
![2016-08-08 15_12_08-sonarqube](https://cloud.githubusercontent.com/assets/2972876/17498207/b8ad1c2c-5d7a-11e6-8b42-0e0fb6628a01.png)

**Comment by mjdetullio** [comment]
There is no dedicated file.  Global settings are defined in the server UI and they can be overridden by the scanner parameters.

You may want to ask the mailing list about your use case https://groups.google.com/forum/#!forum/sonarqube

Or there's an old API for updating properties that is documented here http://docs.sonarqube.org/pages/viewpage.action?pageId=2392170#WebService/api/properties-CreateorUpdateaProperty

**Comment by ddavison** [comment]
perfect, thanks so much for getting back to me so hastily!

i'll see what i can do about utilizing that api there.  in the meantime, i have no problem dealing with the ui for the time being.  

this issue can be closed if you wish! (i noticed you put the label on it, so i won't close it myself)
