### ISSUE TITLE
SonarQube 6.5.1 LTS : java.lang.IllegalStateException

### ISSUE THREAD

**Issue by jvanbouchaute** [SonarQubeCommunity/sonar-build-breaker#14]
Hi.

After updating to 5.6.1 LTS , our maven sonar analysis jobs fail with following errors : 
I installed todays's plugin snapshot build (2.2 - from source ) as well , but it keeps failing.

11:17:08 [INFO] [11:17:16.863] Waiting for report processing to complete...
11:17:18 [ERROR] Report processing did not complete successfully: FAILED
11:17:18 [INFO] ------------------------------------------------------------------------
11:17:18 [INFO] Reactor Summary:
11:17:18 [INFO] 
11:17:18 [INFO] XXXX-integration-head ........................... SKIPPED
11:17:18 [INFO] XXXX-integration-head ........................... FAILURE [21.281s]
11:17:18 [INFO] ------------------------------------------------------------------------
11:17:18 [INFO] BUILD FAILURE
11:17:18 [INFO] ------------------------------------------------------------------------
11:17:18 [INFO] Total time: 21.625s
11:17:18 [INFO] Finished at: Tue Aug 30 11:17:26 CEST 2016
11:17:18 [INFO] Final Memory: 26M/1255M
11:17:18 [INFO] ------------------------------------------------------------------------
11:17:18 [ERROR] Failed to execute goal org.codehaus.mojo:sonar-maven-plugin:2.4:sonar (default-cli) on project XXXXXX: Report processing did not complete successfully: FAILED -> [Help 1]
11:17:18 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:sonar-maven-plugin:2.4:sonar (default-cli) on project XXXX: Report processing did not complete successfully: FAILED
11:17:18 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
11:17:18 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
11:17:18 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
11:17:18 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
11:17:18 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
11:17:18 	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
11:17:18 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
11:17:18 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
11:17:18 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
11:17:18 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
11:17:18 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
11:17:18 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
11:17:18 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:17:18 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:17:18 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:17:18 	at java.lang.reflect.Method.invoke(Method.java:483)
11:17:18 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
11:17:18 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
11:17:18 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
11:17:18 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
11:17:18 Caused by: org.apache.maven.plugin.MojoExecutionException: Report processing did not complete successfully: FAILED
11:17:18 	at org.codehaus.mojo.sonar.bootstrap.ExceptionHandling.handle(ExceptionHandling.java:42)
11:17:18 	at org.codehaus.mojo.sonar.bootstrap.RunnerBootstraper.execute(RunnerBootstraper.java:135)
11:17:18 	at org.codehaus.mojo.sonar.SonarMojo.execute(SonarMojo.java:136)
11:17:18 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
11:17:18 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
11:17:18 	... 19 more
11:17:18 Caused by: java.lang.IllegalStateException: Report processing did not complete successfully: FAILED
11:17:18 	at org.sonar.plugins.buildbreaker.QualityGateBreaker.getAnalysisId(QualityGateBreaker.java:152)
11:17:18 	at org.sonar.plugins.buildbreaker.QualityGateBreaker.execute(QualityGateBreaker.java:108)
11:17:18 	at org.sonar.plugins.buildbreaker.QualityGateBreaker.executeOn(QualityGateBreaker.java:95)
11:17:18 	at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:65)
11:17:18 	at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:55)
11:17:18 	at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:87)
11:17:18 	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
11:17:18 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
11:17:18 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
11:17:18 	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
11:17:18 	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
11:17:18 	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
11:17:18 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
11:17:18 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
11:17:18 	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
11:17:18 	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
11:17:18 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
11:17:18 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
11:17:18 	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
11:17:18 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
11:17:18 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:79)
11:17:18 	at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
11:17:18 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:17:18 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:17:18 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:17:18 	at java.lang.reflect.Method.invoke(Method.java:483)
11:17:18 	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
11:17:18 	at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
11:17:18 	at java.security.AccessController.doPrivileged(Native Method)
11:17:18 	at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
11:17:18 	at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
11:17:18 	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
11:17:18 	at org.sonar.runner.api.Runner.execute(Runner.java:100)
11:17:18 	at org.codehaus.mojo.sonar.bootstrap.RunnerBootstraper.execute(RunnerBootstraper.java:131)
11:17:18 	... 22 more
11:17:18 [ERROR] 
11:17:18 [ERROR] 
11:17:18 [ERROR] For more information about the errors and possible solutions, please read the following articles:
11:17:18 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
11:17:18 [ERROR]

**Comment by mjdetullio** [comment]
This is because the server side background task for your project is failing.  You need to check the logs there and fix that problem first.  The report processing step is when SQ computes the quality gate status.

**Comment by rubensgomes** [comment]
This issue happens when I am building multi-module projects where modules share the same project source directory.

**Comment by mayankramani** [comment]
Hi Team,

I am facing same issue on multi-module app .Can someone help to find a solution ?

Regards,
Mayank
