### ISSUE TITLE
Allow to break build on preview analysis runs

### ISSUE THREAD

**Issue by ghenzler** [SonarQubeCommunity/sonar-build-breaker#19]
Currently the build breaker ignores preview analysis runs completely:
https://github.com/SonarQubeCommunity/sonar-build-breaker/blob/2.1/src/main/java/org/sonar/plugins/buildbreaker/QualityGateBreaker.java#L86

Albeit it seems not to be possible to check against a quality gate in this mode, it is still possible to check against basic violations local to a certain file. A PostJob can receive these issues via constructor injection, see e.g. https://github.com/AmadeusITGroup/sonar-stash/blob/1.2.0/src/main/java/org/sonar/plugins/stash/StashIssueReportingPostJob.java#L25 for where this works. 

I think it would be useful to introduce a BasicIssuesBuildBreaker class (that only becomes active for preview runs) and a configuration what severity should break the build (e.g. if configured to MAJOR, all issues equal or more severe than MAJOR should break the build). Having this in place would be great for feature branch validation and would avoid
* the need to create a branch in Sonar for every feature branch
* the performance penality to run a full sonar analysis on every feature branch build

**Comment by ghenzler** [comment]
Created https://github.com/SonarQubeCommunity/sonar-build-breaker/pull/20 (tested with SonarQube 5.6.3 LTS). To make the build breaker plugin run on preview mode, excludePlugins still has to be provided as follows:  `-Dsonar.preview.excludePlugins=devcockpit,buildstability,pdfreport,report,scmstats,views,jira`

**Comment by prabhakar349** [comment]
@ghenzler  can give some more details on why it is not possible to check against a quality gate in preview mode ?

**Comment by ghenzler** [comment]
@prabhakar349 Well, the first link in the description points to the following code: `if(!analysisMode.isPublish()) { ... return; }` - `publish` is the mode for a full run, for non-publish modes it will never break that way.

**Comment by IronBy** [comment]
Hello. Is there any update on when you are going to release 2.2 with the fix? We're looking forward to using it.

**Comment by ahiggins78** [comment]
Does the "Issues severity failure level" correspond to what is in the Quality Profile that is enabled?  I guess I'm just trying to figure out what it's looking at to determine if it's an issue or not.

**Comment by ghenzler** [comment]
The quality profile is respected (but the quality gate is not because that's only possible on a full run currently)

**Comment by ahiggins78** [comment]
Thank you!
