### ISSUE TITLE
License Information on Using Code

### ISSUE THREAD

**Issue by ojblass** [SonarQubeCommunity/sonar-build-breaker#21]
Currently this code is not released under any open source license.  For organizations to benefit from the plugin they will need legal assurances about code use.

**Comment by mjdetullio** [comment]
I think what you mean is there is not an explicitly provided LICENSE file, which I agree should be added.  But, you're incorrect in saying it is not released under a license.  The license is defined in the POM and the license is also at the top of each source file.  I'm curious if there's a plugin like the `com.mycila:license-maven-plugin` (that currently ensures the headers are synced to the POM settings) to check a LICENSE file as well.  I'll look into that.

**Comment by mjdetullio** [comment]
`LICENSE` file added
