### ISSUE TITLE
Any ETA for next Release?

### ISSUE THREAD

**Issue by tknerr** [SonarQubeCommunity/sonar-build-breaker#24]
Just wanted to try out the `-Dsonar.buildbreaker.preview.issuesSeverity` flag, but nothing happened. 

After looking at the v2.1 version tag, it seems this functionality is new in master but not released yet.

Any ETA for the next release of this plugin?

**Comment by mjdetullio** [comment]
https://github.com/SonarQubeCommunity/sonar-build-breaker/releases/tag/2.2

**Comment by tknerr** [comment]
@mjdetullio thanks! 👍
