### ISSUE TITLE
Disable Build Breaker Plugin

### ISSUE THREAD

**Issue by rubensgomes** [SonarQubeCommunity/sonar-build-breaker#29]
I installed the sonar build breaker on SonarQube Version 6.7 (build 33306).  That is, I placed the sonar-build-breaker-plugin-2.2.jar plugin jar file in the /opt/sonarqube/extensions/plugins, and restarted the server.  After doing that I noticed the buildbreaker running during the  "verify" phase of my Maven build (see printouts below).

Question:  Is there a way to disable the buildbreaker from running by default; that is, for every maven build that involves calling the "sonar:sonar" goal  during verify?  That is, is there a property that I can configure on the server side to disable this plugin from running as default?  And a property I can set on my maven build to enable the buildbreaker plugin from my Maven build?

[INFO] Executing post-job org.sonar.plugins.buildbreaker.QualityGateBreaker
[INFO] Waiting for report processing to complete...
[INFO] Quality gate status: ERROR
[ERROR] Condition Coverage: 6.1 < 80
[ERROR] [BUILD BREAKER] Project did not meet 1 conditions
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

Thanks,

Rubens Gomes
www.rubens-gomes.com

**Comment by sesturm** [comment]
Did you tried -Dsonar.buildbreaker.skip=true ?
This is also a serverside option.

Ragards,
Sebastian
