### ISSUE TITLE
Build breaker not working

### ISSUE THREAD

**Issue by MirzaSB** [SonarQubeCommunity/sonar-build-breaker#31]
Hello,

I setup SonarQube locally, and I copied the extention files into the correct directory.

I added 2 unused variables into my code, and executed a maven clean test command like below:

mvn --settings settings/settings.xml clean verify sonar:sonar -DskipTests -Dsonar.analysis.mode=issues

The build passes even though I see 2 major issues in the Sonar page (localhost:9000).

I want the build to break, but its not happening. What am I doing wrong?

**Comment by SMUnlimited** [comment]
You need to set the property "sonar.buildbreaker.preview.issuesSeverity" when using "preview" or "issues" analysis modes.

**Comment by MirzaSB** [comment]
I added that already. I set it to "info". The same issue persists.

**Comment by MirzaSB** [comment]
Can someone please help?

I tried the following command:

`mvn clean verify sonar:sonar -DskipTests -Dsonar.buildbreaker.preview.issuesSeverity=info -Dsonar.analysis.mode=preview`

I get the "BUILD FAILURE" in the command line, but then when I access the http://localhost:9000 sonarqube page, the project data does not even appear (like showing what code smells or bugs were found).

The log that I got is below:

https://gist.github.com/MirzaSB/f6081c214fdb17849f93923737e013ec

**Comment by SMUnlimited** [comment]
This is the correct behaviour, it just fails the maven build. Preview/issues mode does not upload anything to sonarqube.

**Comment by MirzaSB** [comment]
@SMUnlimited 

Hello Liam,

Thank you for getting back to me.

This is what I am trying to do.

1) I have a Java code base.
2) I want to run Sonar scanner with the build breaker plugin.
3) If there are any kind of issues like code smells, minor or major issues, then it should break the build (which it is doing).
4) But I also want to see what the issues are on the sonar page or any other report. How would I be able to do this?

**Comment by SMUnlimited** [comment]
You will have to do it in 2 mvn commands, you wont be able to do it in one. 1 doing the normal mvn sonar:sonar to upload to the server, followed by the 1 above to break the build.

**Comment by MirzaSB** [comment]
@SMUnlimited 

If I do a mvn sonar:sonar, that breaks the build itself bcos I setup the build breaker plugin properties in the pom.xml file.

Can you tell me how to setup the pom.xml and the commands such that your earlier idea works?

**Comment by MirzaSB** [comment]
I decided to use a custom Quality Gate to fail builds instead of using the build breaker plugin. I will close this issue now.
