### ISSUE TITLE
Migration to Sonar 5.2

### ISSUE THREAD

**Issue by nilsmahlstaedt** [SonarQubeCommunity/sonar-build-breaker#4]
Hey I wanted to ask, if you are plannig to migrate the Build Braker Plugin to Sonarqube 5.2/5.3?

**Comment by mjdetullio** [comment]
Due to shortcomings in the SQ platform, it is not possible to make it compatible with 5.2.

**Comment by mjdetullio** [comment]
It appears SonarSource has decided not publish the plugin the update center.  If you'd like, you can offer your opinion in one of these threads:

https://groups.google.com/d/topic/sonarqube/TcMaZtLCGfs/discussion
https://groups.google.com/d/topic/sonarqube/gR07SqqpAyQ/discussion
https://groups.google.com/d/topic/sonarqube/T8ub7NOfd2g/discussion
