### ISSUE TITLE
sonar.buildbreaker.skip for SonarQube 5.3

### ISSUE THREAD

**Issue by fluidjeel** [SonarQubeCommunity/sonar-build-breaker#5]
This is more of a query than an issue. Has the buildbreaker skip been tested for SQ5.3. I didnt work for me, but then I havent tested in any other version as well. So i'm not sure if my implementation is incorrect or if this feaure is in-compatible with SQ 5.3

**Comment by mjdetullio** [comment]
Yes, I've tested it, and there are unit tests for it.  Depending on which SonarQube Scanner you're using, make sure the property is provided correctly.  If you're setting it via the SQ server UI and not via property, then this would be a bug with the SonarQube Scanner not properly retrieving settings from the server.

https://github.com/SonarQubeCommunity/sonar-build-breaker/blob/2.0/src/main/java/org/sonar/plugins/buildbreaker/QualityGateBreaker.java#L76

**Comment by fluidjeel** [comment]
Tested. It works fine
