### ISSUE TITLE
SonarQube 5.4 support

### ISSUE THREAD

**Issue by BattleLoot** [SonarQubeCommunity/sonar-build-breaker#6]
Do You plan add plugin supporting for the SonarQube 5.4?

Thanks!

**Comment by mjdetullio** [comment]
It should work.  I haven't tested against the final release, but it worked
on a pre-release version.  Once I verify I will update the readme.

**Comment by BattleLoot** [comment]
Yep, plugin v 2.0 works with SonarQube 5.4.

Thanks!
