### ISSUE TITLE
Build Breaker 2.0 not compatible with 5.5-RC1

### ISSUE THREAD

**Issue by jabbera** [SonarQubeCommunity/sonar-build-breaker#9]
```
Caused by: java.lang.NoSuchMethodError: org.sonar.api.batch.SensorContext.analysisMode()Lorg/sonar/api/batch/AnalysisMode;
  at org.sonar.plugins.buildbreaker.QualityGateBreaker.executeOn(QualityGateBreaker.java:71)
  at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:65)
  at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:55)
```

**Comment by henryju** [comment]
org.sonar.api.batch.SensorContext.analysisMode() is part of a @Beta API so we have removed it without notice. I'm sorry for that but the fix is easy. You can access AnalysisMode component using pico injection in your constructor.

**Comment by mjdetullio** [comment]
@henryju Yes, I now see that it is a beta API, however my code uses the `org.sonar.api.batch.SensorContext` API, which is not in beta.  It appears that this interface extends the beta API `org.sonar.api.batch.sensor.SensorContext`:

https://github.com/SonarSource/sonarqube/blob/5.3/sonar-plugin-api/src/main/java/org/sonar/api/batch/SensorContext.java#L36

This is confusing and was not immediately apparent when using the non-beta API.  I understand switching to use the AnalysisMode via injection is an easy fix, but please consider this problem when making non-beta interfaces extend beta ones.

**Comment by mjdetullio** [comment]
@jabbera Please use 2.1-RC1 of the plugin.  I will do a full release after SQ 5.5 release.

https://github.com/SonarQubeCommunity/sonar-build-breaker/releases/tag/2.1-rc1

**Comment by jabbera** [comment]
Thanks. Wil give it a try tomorrow

**Comment by henryju** [comment]
@mjdetullio I agree this is a very bad situation. Sorry again for the inconvenience. We'll try to cleanup all this API mess in 5.6.
